[[entry]]
played_at = "2026-05-08T10:23:05Z"
path = "Partita - Argerich.flac"
title = "Bach: Partita for keyboard No. 2 | Martha Argerich, piano"
artist = "DW Classical Music"
genre = "Music"
year = 1
